### PR TITLE
Use license in package.json

### PR DESCRIPTION
**Pull request by SimenB**
Array deprecated in `npm@2.10.0`

https://github.com/npm/npm/blob/master/doc/files/package.json.md#license

### CODE REVIEW

**Comment by SimenB** [comment]
@sokra Why was this not merged?

**Comment by sokra** [comment]
Wrong button ;-) sorry

**Comment by SimenB** [comment]
@sokra Ah, I see you ran `npm init` or something. Conflict caused by tabs vs. spaces :smile: 

As that command also added `license`, this PR is changed to just remove redundant `licenses`.

**Comment by sokra** [comment]
ah ok... Thanks

**Pull request merged**
